# Change these first
owner: valentinbinotto
repo: status

sites:
  - name: v4zen.com
    url: https://v4zen.com
    icon: https://raw.githubusercontent.com/valentinbinotto/status/master/assets/icon.png
  - name: v434project.com
    url: https://v434project.com
    icon: https://raw.githubusercontent.com/valentinbinotto/status/master/assets/icon.png
  - name: v434.net
    url: https://v434.net
    icon: https://raw.githubusercontent.com/valentinbinotto/status/master/assets/icon.png
  - name: V434Space
    url: https://v434.cloud.mattermost.com
    icon: https://raw.githubusercontent.com/valentinbinotto/status/master/assets/icon.png
  - name: blog.vlentin.com
    url: https://blog.vlentin.com
    icon: https://raw.githubusercontent.com/valentinbinotto/status/master/assets/icon.png
  - name: v4jp.com
    url: https://v4jp.com
    icon: https://raw.githubusercontent.com/valentinbinotto/status/master/assets/icon.png

status-website:
  theme: light
  cname: status.v434project.com
  logoUrl: https://raw.githubusercontent.com/valentinbinotto/status/master/assets/v434logosvg.svg
  # faviconSvg: https://raw.githubusercontent.com/valentinbinotto/status/master/assets/v434logosvg.svg
  name: V434 Project
  introTitle: "**V434 Project** status page"
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: Webpage
      href: https://v434project.com
  metaTags:
    - name: "robots"
      content: "noindex"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
