# Change these first
owner: valentinbinotto
repo: status

sites:
  - name: v4zen.com
    url: https://v4zen.com
  - name: v434project.com
    url: https://v434project.com
  - name: v434.net
    url: https://v434.net
  - name: V434Space
    url: https://v434.cloud.mattermost.com
  - name: blog.vlentin.com
    url: https://blog.vlentin.com
  - name: v4jp.com
    url: https://v4jp.com

status-website:
  theme: light
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.v434project.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: V434 Project
  introTitle: "**V434 Project** status page"
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
